name: Publish To Website

on:
  push:
    branches:
      - master

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          path: source

      - name: Checkout website repo
        uses: actions/checkout@v4
        with:
          repository: HaHussain/Mana-And-Momentum-Website
          token: ${{ secrets.API_TOKEN_GITHUB }}
          ref: v4
          path: dest

      - name: Sync files with deletions
        run: |
          rsync -av --delete source/ dest/content/

      - name: Commit & Push changes
        run: |
          cd dest
          git config user.name "github-actions[bot]"
          git config user.email "workflows@test.com"
          git add -A content/

          if ! git diff --cached --quiet; then
            git commit -m "${{ github.event.head_commit.message }}"
            git push origin v4
          else
            echo "No changes to commit"
          fi

